/* INSERE DADOS NA TABELA DE HÓSPEDES */
DECLARE
  VCOD_HOSPEDE NUMBER;
BEGIN
  VCOD_HOSPEDE := HOTELDB.HOSPEDE_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.HOSPEDE VALUES(
    VCOD_HOSPEDE, 'JOÃO SILVA', 'SOUZA', 'joaosilva@email.com', '27999999999', '12345678900', SYSDATE
  );
END;
--
DECLARE
  VCOD_HOSPEDE NUMBER;
BEGIN
  VCOD_HOSPEDE := HOTELDB.HOSPEDE_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.HOSPEDE VALUES(
    VCOD_HOSPEDE, 'MARIA OLIVEIRA', 'SANTOS', 'mariaoliveira@email.com', '27988888888', '98765432100', SYSDATE
  );
END;
--
DECLARE
  VCOD_HOSPEDE NUMBER;
BEGIN
  VCOD_HOSPEDE := HOTELDB.HOSPEDE_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.HOSPEDE VALUES(
    VCOD_HOSPEDE, 'CARLOS PEREIRA', 'MACHADO', 'carlosp@email.com', '27997777777', '45612378900', SYSDATE
  );
END;
--
DECLARE
  VCOD_HOSPEDE NUMBER;
BEGIN
  VCOD_HOSPEDE := HOTELDB.HOSPEDE_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.HOSPEDE VALUES(
    VCOD_HOSPEDE, 'ANA LIMA', 'FERREIRA', 'analima@email.com', '27996666666', '78965412300', SYSDATE
  );
END;
--
/* INSERE DADOS NA TABELA DE TIPOS DE QUARTO */
DECLARE
  VCOD_TIPO NUMBER;
BEGIN
  VCOD_TIPO := HOTELDB.TIPO_QUARTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.TIPO_QUARTO VALUES(
    VCOD_TIPO, 'STANDARD', 'Quarto simples com 1 cama de casal', 2, 150.00, SYSDATE
  );
END;
--
DECLARE
  VCOD_TIPO NUMBER;
BEGIN
  VCOD_TIPO := HOTELDB.TIPO_QUARTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.TIPO_QUARTO VALUES(
    VCOD_TIPO, 'LUXO', 'Quarto com vista para o mar e varanda', 3, 350.00, SYSDATE
  );
END;
--
DECLARE
  VCOD_TIPO NUMBER;
BEGIN
  VCOD_TIPO := HOTELDB.TIPO_QUARTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.TIPO_QUARTO VALUES(
    VCOD_TIPO, 'FAMÍLIA', 'Quarto com 2 camas de casal e frigobar', 4, 450.00, SYSDATE
  );
END;
--
DECLARE
  VCOD_TIPO NUMBER;
BEGIN
  VCOD_TIPO := HOTELDB.TIPO_QUARTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.TIPO_QUARTO VALUES(
    VCOD_TIPO, 'MASTER', 'Suíte completa com jacuzzi e varanda', 2, 600.00, SYSDATE
  );
END;
--
/* INSERE DADOS NA TABELA DE QUARTOS */
DECLARE
  VCOD_QUARTO NUMBER;
BEGIN
  VCOD_QUARTO := HOTELDB.QUARTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.QUARTO VALUES(VCOD_QUARTO, '101', 1, 1, 'LIVRE', SYSDATE);
END;
--
DECLARE
  VCOD_QUARTO NUMBER;
BEGIN
  VCOD_QUARTO := HOTELDB.QUARTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.QUARTO VALUES(VCOD_QUARTO, '102', 1, 1, 'OCUPADO', SYSDATE);
END;
--
DECLARE
  VCOD_QUARTO NUMBER;
BEGIN
  VCOD_QUARTO := HOTELDB.QUARTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.QUARTO VALUES(VCOD_QUARTO, '201', 2, 2, 'LIVRE', SYSDATE);
END;
--
DECLARE
  VCOD_QUARTO NUMBER;
BEGIN
  VCOD_QUARTO := HOTELDB.QUARTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.QUARTO VALUES(VCOD_QUARTO, '202', 2, 2, 'MANUTENÇÃO', SYSDATE);
END;
--
DECLARE
  VCOD_QUARTO NUMBER;
BEGIN
  VCOD_QUARTO := HOTELDB.QUARTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.QUARTO VALUES(VCOD_QUARTO, '301', 3, 3, 'LIVRE', SYSDATE);
END;
--
DECLARE
  VCOD_QUARTO NUMBER;
BEGIN
  VCOD_QUARTO := HOTELDB.QUARTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.QUARTO VALUES(VCOD_QUARTO, '302', 3, 4, 'OCUPADO', SYSDATE);
END;
--
/* INSERE DADOS NA TABELA DE RESERVAS */
DECLARE
  VCOD_RESERVA NUMBER;
BEGIN
  VCOD_RESERVA := HOTELDB.RESERVA_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.RESERVA VALUES(
    VCOD_RESERVA, 1, 2, TO_DATE('2025-10-20','YYYY-MM-DD'), TO_DATE('2025-10-25','YYYY-MM-DD'), 2, 'CONFIRMADA', 1750.00, SYSDATE
  );
END;
--
DECLARE
  VCOD_RESERVA NUMBER;
BEGIN
  VCOD_RESERVA := HOTELDB.RESERVA_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.RESERVA VALUES(
    VCOD_RESERVA, 2, 3, TO_DATE('2025-11-01','YYYY-MM-DD'), TO_DATE('2025-11-07','YYYY-MM-DD'), 3, 'CONFIRMADA', 2700.00, SYSDATE
  );
END;
--
DECLARE
  VCOD_RESERVA NUMBER;
BEGIN
  VCOD_RESERVA := HOTELDB.RESERVA_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.RESERVA VALUES(
    VCOD_RESERVA, 3, 1, TO_DATE('2025-12-10','YYYY-MM-DD'), TO_DATE('2025-12-15','YYYY-MM-DD'), 2, 'PENDENTE', 750.00, SYSDATE
  );
END;
--
DECLARE
  VCOD_RESERVA NUMBER;
BEGIN
  VCOD_RESERVA := HOTELDB.RESERVA_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.RESERVA VALUES(
    VCOD_RESERVA, 4, 4, TO_DATE('2025-12-22','YYYY-MM-DD'), TO_DATE('2025-12-30','YYYY-MM-DD'), 2, 'CANCELADA', 0.00, SYSDATE
  );
END;
--
/* INSERE DADOS NA TABELA DE PAGAMENTOS */
DECLARE
  VCOD_PAGAMENTO NUMBER;
BEGIN
  VCOD_PAGAMENTO := HOTELDB.PAGAMENTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.PAGAMENTO VALUES(
    VCOD_PAGAMENTO, 1, 1750.00, TO_DATE('2025-10-18','YYYY-MM-DD'), 'CARTÃO DE CRÉDITO', 'PAGO'
  );
END;
--
DECLARE
  VCOD_PAGAMENTO NUMBER;
BEGIN
  VCOD_PAGAMENTO := HOTELDB.PAGAMENTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.PAGAMENTO VALUES(
    VCOD_PAGAMENTO, 2, 2700.00, TO_DATE('2025-10-25','YYYY-MM-DD'), 'PIX', 'PAGO'
  );
END;
--
DECLARE
  VCOD_PAGAMENTO NUMBER;
BEGIN
  VCOD_PAGAMENTO := HOTELDB.PAGAMENTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.PAGAMENTO VALUES(
    VCOD_PAGAMENTO, 3, 750.00, TO_DATE('2025-12-09','YYYY-MM-DD'), 'DINHEIRO', 'PENDENTE'
  );
END;
--
DECLARE
  VCOD_PAGAMENTO NUMBER;
BEGIN
  VCOD_PAGAMENTO := HOTELDB.PAGAMENTO_ID_SEQ.NEXTVAL;

  INSERT INTO HOTELDB.PAGAMENTO VALUES(
    VCOD_PAGAMENTO, 4, 0.00, TO_DATE('2025-12-21','YYYY-MM-DD'), 'CARTÃO DE DÉBITO', 'CANCELADO'
  );
END;
