/*INSERE DADOS NA TABELA DE HÓSPEDES*/
INSERT INTO HOTELDB.HOSPEDE VALUES(HOSPEDE_ID_SEQ.NEXTVAL, 'JOÃO SILVA', 'SOUZA', 'joaosilva@email.com', '27999999999', '12345678900', SYSDATE);
INSERT INTO HOTELDB.HOSPEDE VALUES(HOSPEDE_ID_SEQ.NEXTVAL, 'MARIA OLIVEIRA', 'SANTOS', 'mariaoliveira@email.com', '27988888888', '98765432100', SYSDATE);
INSERT INTO HOTELDB.HOSPEDE VALUES(HOSPEDE_ID_SEQ.NEXTVAL, 'CARLOS PEREIRA', 'MACHADO', 'carlosp@email.com', '27997777777', '45612378900', SYSDATE);
INSERT INTO HOTELDB.HOSPEDE VALUES(HOSPEDE_ID_SEQ.NEXTVAL, 'ANA LIMA', 'FERREIRA', 'analima@email.com', '27996666666', '78965412300', SYSDATE);

/*INSERE DADOS NA TABELA DE TIPOS DE QUARTO*/
INSERT INTO HOTELDB.TIPO_QUARTO VALUES(TIPO_QUARTO_ID_SEQ.NEXTVAL, 'STANDARD', 'Quarto simples com 1 cama de casal', 2, 150.00, SYSDATE);
INSERT INTO HOTELDB.TIPO_QUARTO VALUES(TIPO_QUARTO_ID_SEQ.NEXTVAL, 'LUXO', 'Quarto com vista para o mar e varanda', 3, 350.00, SYSDATE);
INSERT INTO HOTELDB.TIPO_QUARTO VALUES(TIPO_QUARTO_ID_SEQ.NEXTVAL, 'FAMÍLIA', 'Quarto com 2 camas de casal e frigobar', 4, 450.00, SYSDATE);
INSERT INTO HOTELDB.TIPO_QUARTO VALUES(TIPO_QUARTO_ID_SEQ.NEXTVAL, 'MASTER', 'Suíte completa com jacuzzi e varanda', 2, 600.00, SYSDATE);

/*INSERE DADOS NA TABELA DE QUARTOS*/
INSERT INTO HOTELDB.QUARTO VALUES(QUARTO_ID_SEQ.NEXTVAL, '101', 1, 1, 'LIVRE', SYSDATE);
INSERT INTO HOTELDB.QUARTO VALUES(QUARTO_ID_SEQ.NEXTVAL, '102', 1, 1, 'OCUPADO', SYSDATE);
INSERT INTO HOTELDB.QUARTO VALUES(QUARTO_ID_SEQ.NEXTVAL, '201', 2, 2, 'LIVRE', SYSDATE);
INSERT INTO HOTELDB.QUARTO VALUES(QUARTO_ID_SEQ.NEXTVAL, '202', 2, 2, 'MANUTENÇÃO', SYSDATE);
INSERT INTO HOTELDB.QUARTO VALUES(QUARTO_ID_SEQ.NEXTVAL, '301', 3, 3, 'LIVRE', SYSDATE);
INSERT INTO HOTELDB.QUARTO VALUES(QUARTO_ID_SEQ.NEXTVAL, '302', 3, 4, 'OCUPADO', SYSDATE);

/*INSERE DADOS NA TABELA DE RESERVAS*/
INSERT INTO HOTELDB.RESERVA VALUES(RESERVA_ID_SEQ.NEXTVAL, 1, 2, TO_DATE('2025-10-20', 'YYYY-MM-DD'), TO_DATE('2025-10-25', 'YYYY-MM-DD'), 2, 'CONFIRMADA', 1750.00, SYSDATE);
INSERT INTO HOTELDB.RESERVA VALUES(RESERVA_ID_SEQ.NEXTVAL, 2, 3, TO_DATE('2025-11-01', 'YYYY-MM-DD'), TO_DATE('2025-11-07', 'YYYY-MM-DD'), 3, 'CONFIRMADA', 2700.00, SYSDATE);
INSERT INTO HOTELDB.RESERVA VALUES(RESERVA_ID_SEQ.NEXTVAL, 3, 1, TO_DATE('2025-12-10', 'YYYY-MM-DD'), TO_DATE('2025-12-15', 'YYYY-MM-DD'), 2, 'PENDENTE', 750.00, SYSDATE);
INSERT INTO HOTELDB.RESERVA VALUES(RESERVA_ID_SEQ.NEXTVAL, 4, 4, TO_DATE('2025-12-22', 'YYYY-MM-DD'), TO_DATE('2025-12-30', 'YYYY-MM-DD'), 2, 'CANCELADA', 0.00, SYSDATE);

/*INSERE DADOS NA TABELA DE PAGAMENTOS*/
INSERT INTO HOTELDB.PAGAMENTO VALUES(PAGAMENTO_ID_SEQ.NEXTVAL, 1, 1750.00, TO_DATE('2025-10-18', 'YYYY-MM-DD'), 'CARTÃO DE CRÉDITO', 'PAGO');
INSERT INTO HOTELDB.PAGAMENTO VALUES(PAGAMENTO_ID_SEQ.NEXTVAL, 2, 2700.00, TO_DATE('2025-10-25', 'YYYY-MM-DD'), 'PIX', 'PAGO');
INSERT INTO HOTELDB.PAGAMENTO VALUES(PAGAMENTO_ID_SEQ.NEXTVAL, 3, 750.00, TO_DATE('2025-12-09', 'YYYY-MM-DD'), 'DINHEIRO', 'PENDENTE');
INSERT INTO HOTELDB.PAGAMENTO VALUES(PAGAMENTO_ID_SEQ.NEXTVAL, 4, 0.00, TO_DATE('2025-12-21', 'YYYY-MM-DD'), 'CARTÃO DE DÉBITO', 'CANCELADO');

COMMIT;
